// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB55_RdJ15c-0eloICuSs-7hdrlTw2FtKM',
    appId: '1:661008712105:web:dc674b8a9d99bf321244b8',
    messagingSenderId: '661008712105',
    projectId: 'college-locker-app',
    authDomain: 'college-locker-app.firebaseapp.com',
    storageBucket: 'college-locker-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKHMLo6TGvzMWbaf__C8tFREKbryRIAkM',
    appId: '1:661008712105:android:6fe167ac96a8ebf81244b8',
    messagingSenderId: '661008712105',
    projectId: 'college-locker-app',
    storageBucket: 'college-locker-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPP87tlVDvsa6rY_uIN-Koggiu2j152Yk',
    appId: '1:661008712105:ios:381a4b2fde26ca6e1244b8',
    messagingSenderId: '661008712105',
    projectId: 'college-locker-app',
    storageBucket: 'college-locker-app.firebasestorage.app',
    iosBundleId: 'com.example.mylocker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPP87tlVDvsa6rY_uIN-Koggiu2j152Yk',
    appId: '1:661008712105:ios:381a4b2fde26ca6e1244b8',
    messagingSenderId: '661008712105',
    projectId: 'college-locker-app',
    storageBucket: 'college-locker-app.firebasestorage.app',
    iosBundleId: 'com.example.mylocker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB55_RdJ15c-0eloICuSs-7hdrlTw2FtKM',
    appId: '1:661008712105:web:abd3841be6ab9b011244b8',
    messagingSenderId: '661008712105',
    projectId: 'college-locker-app',
    authDomain: 'college-locker-app.firebaseapp.com',
    storageBucket: 'college-locker-app.firebasestorage.app',
  );
}
